language: python
python:
  - "3.6"
services:
  - docker
before_install:
  # Upgrade Docker to work with docker-py.
  - curl https://gist.githubusercontent.com/geerlingguy/ce883ad4aec6a5f1187ef93bd338511e/raw/36612d28981d92863f839c5aefe5b7dd7193d6c6/travis-ci-docker-upgrade.sh | sudo bash
#install dependencies
install:
  - pip install -r requirements.txt
#command to run the testing
script:
  - ./staphb-tk -h
  - ./staphb-wf -h
  - ./staphb-tk spades -v
