language: python
python:
  - "3.7"
  - "3.8"
services:
  - docker
#install dependencies
install:
  - pip install -r requirements.txt
#command to run the testing
script:
  - ./staphb_tk -h
  - ./staphb_wf -h
  - ./staphb_tk spades -v
