language: python
python:
  - "3.6"
services:
  - docker
#install dependencies
install:
  - pip install -r requirements.txt
#command to run the testing
script:
  - ./staphb-tk -h
  - ./staphb-wf -h
  - ./staphb-tk spades -v
