provenance_domain:
  name: "Tredegar: Bioinformatics pipeline for infectious disease WGS data QC"
  version: "v2.0"
  created: "2019-10-10"
  license: "https://www.apache.org/licenses/LICENSE-2.0"
  contributors:
    contributor_01:
      name: "Kevin G. Libuit"
      affiliation: "Division of Consolidated Laboratory Services Richmond VA"
      email: "kevin.libuit@dgs.virginia.gov"
    contributor_02:
      name: "Kelsey Florek"
      affiliation: "Wisconsin State Laboratory of Hygiene Madison WI"
      email: "Kelsey.Florek@slh.wisc.edu"

  review:
    status: "in-review"
    reviewer_comment: ""
    date: "2019-10-10"
    reviewer:
      name: "Rachael St. Jacques"
      affiliation: "Division of Consolidated Laboratory Services Richmond VA"
      email: "rachael.stjacques@dgs.virginia.gov"

parameter_domain: 
  mash:
    docker_container: "staphb/mash"
    tag: "2.1"
    mash_dist:
      db: "/db/RefSeqSketchesDefaults.msh"
      dist_params: ""
    mash_sketch:
      sketch_params: ""

  seqyclean:
    docker_container: "staphb/seqyclean"
    tag: "1.10.09"
    params: "-minlen 25 -qual -c /Adapters_plus_PhiX_174.fasta"

  shovill:
    docker_container: "staphb/shovill"
    tag: "1.0.4"
    #Tredegar v2.0 uses shovill with default parameters
    params: ""

  quast:
    docker_container: "staphb/quast"
    tag: "5.0.2"
    #Tredegar v2.0 uses quast with default parameters
    params: ""

  cg_pipeline:
    docker_container: "staphb/lyveset"
    tag: "1.1.4f"
    params: "--fast"

  serotypefinder: 
    docker_container: "staphb/serotypefinder"
    tag: "1.1"
    params: "-s ecoli -k 95.00 -l 0.60"

  seqsero:
    docker_container: "staphb/seqsero"
    tag: "1.0.1"
    #Tredegar v2.0.1 uses SeqSero with default parameters
    params: ""

  emm-typing-tool:
    docker_comtainer: "staphb/emm-typing-tool"
    #Tredegar v2.0.1 uses the emm typing allele database available at ftp://ftp.cdc.gov/pub/infectious_diseases/biotech/tsemm/trimmed.tfa
    tag: "-m /db/"

io_domain:
  input_subdomain:
  output_subdomain: