provenance_domain:
  name: "Tredegar: Bioinformatics pipeline for infectious disease WGS data QC"
  version: "v2.0.1"
  created: "2019-10-10"
  license: "https://www.apache.org/licenses/LICENSE-2.0"
  contributors:
    contributor_01:
      name: "Kevin G. Libuit"
      affiliation: "Division of Consolidated Laboratory Services Richmond VA"
      email: "kevin.libuit@dgs.virginia.gov"
    contributor_02:
      name: "Kelsey Florek"
      affiliation: "Wisconsin State Laboratory of Hygiene Madison WI"
      email: "Kelsey.Florek@slh.wisc.edu"

  review:
    status: "in-review"
    reviewer_comment: ""
    date: "2019-10-10"
    reviewer:
      name: "Rachael St. Jacques"
      affiliation: "Division of Consolidated Laboratory Services Richmond VA"
      email: "rachael.stjacques@dgs.virginia.gov"

parameter_domain: 
  mash:
    image: "staphb/mash"
    tag: "2.1"

    # mash commands
    mash_sketch:
      # Tredegar uses mash sketch with default parameters
      sketch_params: ""

    mash_dist:
      dist_params: ""
      db: "/db/RefSeqSketchesDefaults.msh"

  seqyclean:
    image: "staphb/seqyclean"
    tag: "1.10.09"
    params:
      minimum_read_length: "25"
      quality_trimming: "-qual"
      contaminants: "/Adapters_plus_PhiX_174.fasta"

  shovill:
    image: "staphb/shovill"
    tag: "1.0.4"
    # Tredegar uses shovill with default parameters
    params: ""

  quast:
    image: "staphb/quast"
    tag: "5.0.2"
    #Tredegar v2.0 uses quast with default parameters
    params: ""

  cg_pipeline:
    image: "staphb/lyveset"
    tag: "1.1.4f"
    params:
      subsample: "--fast"

  serotypefinder:
    image: "staphb/serotypefinder"
    tag: "1.1"
    params:
      species: "ecoli"
      # comment here
      nucleotide_agreement: "95.00"
      percent_coverage: "0.60"
      # Using serotype database made available within the staphb/serotypefinder docker image
      database: "/serotypefinder/database/"

  seqsero:
    image: "staphb/seqsero"
    tag: "1.0.1"
    #Tredegar v2.0.1 uses SeqSero with default parameters
    params: ""

  emm-typing-tool:
    image: "staphb/emm-typing-tool"
    tag: "0.0.1"
    params:
      #Tredegar uses the emm typing allele database made available within the staphb/emm-typing-tool docker image
      database: "/db"

io_domain:
  input_subdomain:
  output_subdomain: